$(document).ready(function(){
    $('.slider').slick({
        arrows:true,
        dots:true,
        adaptiveHeight:true,
        slidesToShow:1,
        slidesToScroll:1,
        speed:500,
        easing:'ease',
        infinite:false,
        initialSlide:0,
        autoplay:true,
        autoplaySpeed:500
    });
});